import Head from 'next/head'
import Header from '@/components/Header/Header'
import { font } from '@/utils/font'
import Hero from '@/sections/Hero'

export default function Home() {
	return (
		<>
			<Head>
				<title>Wiselink - Dark mode</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Header />
			<main className={font.className}>
				<Hero />
			</main>
		</>
	)
}
