import Head from 'next/head'
import { font } from '@/utils/font'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import {
	Hero,
	Features,
	CommercialAttentions,
	Points,
	Sales,
	CloudFeatures,
	Metrics,
	Contact,
} from '@/sections'

export default function Home() {
	return (
		<>
			<Head>
				<title>Wiselink - Dark mode</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Header />
			<main className={font.className}>
				<Hero />
				<Features />
				<CommercialAttentions />
				<Points />
				<Sales />
				<CloudFeatures />
				<Metrics />
				<Contact />
			</main>
			<Footer />
		</>
	)
}
